[tool.poetry]
name = "clan-bot"
version = "1.0.0"
description = "Bot de Telegram para clan"

[tool.poetry.dependencies]
python = "^3.11"
python-telegram-bot = "20.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
